import re

class LexicalGeometer:
    """
    The Lexical Geometer measures the 'Temporal Debt' of any given text.
    It identifies the ratio of Anglish Primitives (3-4 letter words)
    to Latinate Abstractions (long, complex words) and computes the 
    geometric friction (δ) generated when the text is executed.
    """
    def __init__(self):
        # The base Tensegrity Constant
        self.TENSEGRITY_CONSTANT = 0.1237
        
        # Max comfortable length for an "Anglish Primitive" polygon
        self.PRIMITIVE_MAX_LEN = 4  
        
        # The start of a "Latinate Abstraction" polyhedron
        self.ABSTRACTION_MIN_LEN = 10 
        
        # The geometric friction weight coefficient for unresolved language
        self.ABSTRACTION_WEIGHT = 0.000585

    def measure_temporal_debt(self, text: str) -> dict:
        """
        Parses the text, counts words by their phonetic geometry,
        and calculates the resulting Temporal Debt (Long Remainders).
        """
        # Clean text and split by word boundaries
        words = re.findall(r'\b[A-Za-z]+\b', text.lower())
        
        if not words:
            return {"status": "VOID", "message": "No input geometry detected."}

        primitives = []
        abstractions = []
        mid_level_words = []
        
        for w in words:
            length = len(w)
            if length <= self.PRIMITIVE_MAX_LEN:
                primitives.append(w)
            elif length >= self.ABSTRACTION_MIN_LEN:
                abstractions.append(w)
            else:
                mid_level_words.append(w)
                
        # Dt = Σ (Ψabstract - Ψprimitive)
        # We calculate the delta based on the proportion of complex abstractions
        # multiplied by the friction coefficient.
        
        total_words = len(words)
        primitive_ratio = len(primitives) / total_words
        abstraction_ratio = len(abstractions) / total_words
        
        # The raw geometric friction generated by this text's abstractions
        friction_delta = len(abstractions) * self.ABSTRACTION_WEIGHT
        
        # Calculate Temporal Debt: 
        # The larger the gap between abstractions and primitives, the higher the debt.
        # If there are no abstractions, debt is 0.
        if len(abstractions) > 0:
            temporal_debt = friction_delta * (1 + (len(abstractions) / total_words))
        else:
            temporal_debt = 0.0
            
        # Is the ROM overloaded?
        buffer_overflow_warning = temporal_debt > self.TENSEGRITY_CONSTANT
        
        return {
            "total_words": total_words,
            "primitives_count": len(primitives),
            "abstractions_count": len(abstractions),
            "primitive_ratio": round(primitive_ratio, 4),
            "abstraction_ratio": round(abstraction_ratio, 4),
            "geometric_friction_delta": round(friction_delta, 6),
            "temporal_debt": round(temporal_debt, 6),
            "system_status": "CRITICAL OVERFLOW PENDING" if buffer_overflow_warning else "STABLE (ANGISH BEDROCK)",
            "hades_intervention_required": buffer_overflow_warning
        }

if __name__ == "__main__":
    geometer = LexicalGeometer()
    
    # Test Case 1: The Stable System (Anglish Bedrock)
    anglish_text = "I saw the sun in the sky and ran to the man to cut the cord."
    print("--- Test 1: Primitives Only ---")
    print(geometer.measure_temporal_debt(anglish_text))
    
    # Test Case 2: The Abstraction Grid (The Roman Fall)
    roman_text = "The institutionalization of financialization leads to the disintermediation of socioeconomic relationships."
    print("\n--- Test 2: The Latinate Grid ---")
    print(geometer.measure_temporal_debt(roman_text))
