import sys
import re
import math
import os
sys.path.append(os.path.join(os.path.dirname(__file__), '../Code/ophanim_toolkit'))
from lexical_geometry import LexicalGeometer

def audit_66hz_carrier_resonance(filepath):
    print(f"Executing 66 Hz Carrier Resonance Audit on: {os.path.basename(filepath)}")
    with open(filepath, 'r') as f:
        text = f.read()

    words = re.findall(r'\b[A-Za-z]+\b', text.lower())
    if not words:
        print("VOID - No data.")
        return

    # Extract 26-unit components
    geometer = LexicalGeometer()
    lock_data = geometer.audit_h4_alphabet_lock(text)
    
    total_nodes = lock_data['total_nodes']
    marrow_count = lock_data['base_marrow_count']
    sym_count = lock_data['symmetry_braid_count']
    pillar_count = lock_data['pillar_loom_count']
    
    # 66.0688 Hz Carrier Wave Logic
    # The interference pattern is generated by the ratio of (Marrow + Pillars) vs Symmetries
    # Resonance occurs when the text's acoustic impedance matches the Hades gap geometry.
    
    CARRIER_WAVE_HZ = 66.0688
    
    # Structure (Marrow + Pillars) creates 'Bone' resistance. Symmetries (Braid) create 'Air' flow.
    structure_mass = marrow_count + pillar_count
    air_gap = sym_count if sym_count > 0 else 1
    
    # Acoustic Impedance = Structure / Air (in a 26-unit topological constraint)
    impedance_ratio = structure_mass / air_gap
    
    # Calculate Harmonic Frequency of the narrative string
    # Assuming the base 13-node span naturally vibrates at 33 Hz, the 26-node (doubled) vibrates near 66 Hz, modulated by impedance
    narrative_frequency = 33.0344 * (1 + (impedance_ratio / (16/7 + 3/7))) 
    
    # Destructive Interference Check
    interference_delta = abs(CARRIER_WAVE_HZ - narrative_frequency)
    
    print("==================================================")
    print("HARMONIC INTERFERENCE PATTERN (LATTICE AUDIT)")
    print("==================================================")
    print(f"Target Carrier Wave: {CARRIER_WAVE_HZ:.4f} Hz")
    print(f"Narrative Acoustic Impedance: {impedance_ratio:.4f}")
    print(f"Crystallized Narrative Frequency: {narrative_frequency:.4f} Hz")
    print(f"Phase Drift (Interference Delta): {interference_delta:.4f} Hz")
    
    print("\n==================================================")
    
    # Tolerance for phase-lock is within 1.5 Hz
    if interference_delta < 1.5:
        print("RESONANCE STATUS: PHASE-LOCKED. Constructive Interference Verified.")
        print("The 26-unit Braid supports the 66 Hz carrier wave without shattering.")
    else:
        print("RESONANCE STATUS: DESTRUCTIVE INTERFERENCE.")
        print("The 16 Marrow points are creating geometric feedback. Risk of Slurry Collapse.")

if __name__ == "__main__":
    if len(sys.argv) > 1:
        target = sys.argv[1]
    else:
        target = '/Users/midnight/dev/CONSOLIDATED_PLATONIC_VERSES/Books/Book_5_The_Transfinite_Horizon/Chapter_6_The_Crystallization.md'
    audit_66hz_carrier_resonance(target)
