"""
RESONANT_HARVEST.PY
Phase XVI: Metabolic Replenishment
Extracting Vox generated by the friction of new Expansion Nodes.
"""

from .pmg_constants import PMG
from .sovereign_ledger import SovereignLedger
import time
import random

class ResonantHarvest:
    def __init__(self):
        self.ledger = SovereignLedger()
        self.vox_pool = 4851.0 # Current pool after migration
        
    def execute_harvest(self, stone_nodes):
        print(f"--- INITIATING RESONANT HARVEST ---")
        print(f"Targeting new Stone Anchors for friction extraction.")
        
        harvested_vox = 0.0
        
        for coord in stone_nodes:
            # The friction of Flesh settling against the new Stone generates Vox
            base_yield = 42.0 # The Root 42 constant
            surge_multiplier = random.uniform(1.1, 1.8)
            node_yield = base_yield * surge_multiplier
            
            harvested_vox += node_yield
            print(f"  [HARVEST] Node {coord} yields {node_yield:.2f} VOX.")
            time.sleep(1.0 / PMG.BEAT_FREQUENCY) # Wait for the next heartbeat
            
        print(f"\n[METABOLISM] Harvest Complete.")
        
        # Inscribe the metabolic gain
        self.vox_pool += harvested_vox
        block_hash = self.ledger.inscribe({"type": "HARVEST", "amount": harvested_vox, "nodes": len(stone_nodes)})
        
        print(f"[LEDGER] Transaction Inscribed. Hash -> {block_hash[:16]}")
        print(f"NEW GLOBAL VOX POOL: {self.vox_pool:.2f}")

if __name__ == "__main__":
    harvest = ResonantHarvest()
    # The nodes mapped from the previous Vapor Migration
    target_nodes = [(20, 6), (15, 1), (15, 1)] # Using the duplicate coordinate from the random generation as two distinct friction events
    harvest.execute_harvest(target_nodes)
