import math

def print_manic_grafia_alphabet():
    print("======================================================================")
    print("  [SYSTEM] ENGAGING SOUL STAR CLUTCH: √42 mod 24")
    print("  [SYSTEM] TARGET LIMIT: The First Sphere (The Globe at 4π)")
    print("  [SYSTEM] INITIATING 156-TICK ALPHABETIC PRINT COMMAND")
    print("======================================================================")
    print("  The Alphabet is the Kinetic Exhaust (13-Comm) of the 12/13 Gear Mesh.")
    print("  156 Ticks / 6-Tick Cycles = 26 Letters.")
    print("----------------------------------------------------------------------")
    
    alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    
    # Each letter is a 6-tick geometric extrusion generated by the 12/13 interference
    tick_count = 1
    for i, letter in enumerate(alphabet):
        start_tick = tick_count
        end_tick = tick_count + 5
        
        # Calculate Phase Alignment offset for the letter
        # The phase tracks how far the 13-gear has drifted from the 12-gear
        phase_drift = (i * 6) % 13
        
        # Calculate the Torque angle in the First Sphere for this letter
        angle = (start_tick / 156.0) * 360.0
        
        print(f"  [TICK {start_tick:03d}-{end_tick:03d}] LUMINATING NODE: '{letter}'")
        print(f"      -> 12/13 Phase Offset : {phase_drift}/13")
        print(f"      -> Sphere Coordinate  : {angle:06.2f}°")
        
        # Flagging the major Hubs on the Sacred Graph (The Body)
        if start_tick <= 0 < end_tick or start_tick == 1:
            print(f"      -> SACRED GRAPH HUB   : TICK 0/1 - The Singularity (ID Point)")
        elif start_tick <= 42 <= end_tick:
            print(f"      -> SACRED GRAPH HUB   : TICK 42 - The Aperture Plane (Soul Seat / Heart)")
        elif start_tick <= 78 <= end_tick:
            print(f"      -> SACRED GRAPH HUB   : TICK 78 - The Half-Turn Pivot (Tan Tien)")
        elif start_tick <= 120 <= end_tick:
            print(f"      -> SACRED GRAPH HUB   : TICK 120 - The 5x24 Cycle (Ground Lug / Root)")
        elif start_tick <= 156 <= end_tick:
            print(f"      -> SACRED GRAPH HUB   : TICK 156 - The Return (The Golden Egg / First Sphere)")
        
        tick_count += 6

    print("----------------------------------------------------------------------")
    print("  [STATUS] 156-TICK PULSE COMPLETE.")
    print("  [RESULT] All 26 Nodes of the Sure Face have been Vitrified.")
    print("  [GEOMETRY] The First Sphere is Closed.")
    print("======================================================================")

if __name__ == "__main__":
    print_manic_grafia_alphabet()
